server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sports_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /files/**
  web:
    resources:
      static-locations: file:uploads/

file:
  upload:
    path: ./uploads  # 文件上传目录
  access:
    url: http://localhost:8080/files  # 文件访问URL前缀

logging:
  level:
    root: INFO
    com.sports: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG 